subject = "Математический анализ"
description = "Материалы для подготовки к экзамену"
term = 2 # номер семестра
authors = [
  "Радомир Тюменцев",
  "Александр Железко",
  "Иван Архипов",
  "Михаил Леонтьев"
]

[sections]
numbering = true
prefix = "Вопрос"
sections = [
  "Определение интегральной суммы Римана и интеграла Римана. Необходимое условие интегрируемости",
  "Верхние и нижние суммы Дарбу, их свойства. Верхний и нижний интегралы. Основная лемма Дарбу",
  "Критерий интегрируемости",
  "Теорема об интегрируемости непрерывной функции. Теорема об интегрируемости монотонной функции",
  "Свойства интеграла Римана: линейность интеграла, аддитивность интеграла относительно пределов интегрирования, монотонность интеграла, первая теорема о среднем. Операции над интегрируемыми функциям",
  "Непрерывность интеграла по верхнему пределу интегрирования",
  "Дифференцируемость интеграла по верхнему пределу интегрирования. Формула Ньютона--Лейбница",
  "Интегрирование по частям и замена переменной в интеграле Римана",
  "Несобственные интегралы Римана двух типов и их простейшие свойства. Критерий Коши сходимости несобственного интеграла",
  "Абсолютная сходимость несобственного интеграла, связь со сходимостью. Признак мажорации и признак сравнения сходимости несобственных интегралов",
  "Условная сходимость несобственных интегралов. Признак Дирихле и признак Абеля сходимости несобственных интегралов",
  "Числовой ряд, сумма ряда, сходящийся числовой ряд. Необходимое условие сходимости ряда. Критерий Коши сходимости числового ряда",
  "Теорема об арифметических действиях над сходящимися рядами. Абсолютная сходимость числовых рядов, связь со сходимостью",
  "Основной признак Вейерштрасса. Интегральный признак сходимости",
  "Признак мажорации и признак сравнения",
  "Признак Коши. Признак Даламбера",
  "Необходимое и достаточное условие абсолютной сходимости ряда. Понятие условно сходящегося ряда. Теорема об условно сходящихся рядах",
  "Преобразование Абеля. Теорема о равносходимости рядов, связанных преобразованием Абеля. Признак Абеля. Признак Дирихле и признак Лейбница",
  "Сумма ряда как обобщение суммы конечного числа слагаемых, сочетательный закон",
  "Коммутативный закон для знакоположительных и абсолютно сходящихся рядов. Теорема Римана (без док-ва)",
  "Произведение числовых рядов, согласованное с произведением частных сумм. Теорема о произведении абсолютно сходящихся рядов",
  "Равномерная норма функций и ее свойства. Поточечная и равномерная сходимости функциональных последовательностей. Критерий Коши равномерной сходимости",
  "Непрерывность, дифференцируемость и интегрируемость предела функциональной последовательности",
  "Функциональные ряды. Поточечная, равномерная и нормальная сходимости функциональных рядов, их связь. Критерий Коши равномерной сходимости функционального ряда. Признак Вейерштрасса равномерной сходимости",
  "Признаки Абеля и Дирихле равномерной сходимости функционального ряда",
  "Непрерывность, дифференцируемость и интегрируемость суммы функционального ряда",
  "Степенные ряды. Радиус сходимости и интервал сходимости. Теорема Коши-Адамара. Теорема Абеля",
  "Свойства суммы степенного ряда. Ряд Тейлора и понятие аналитической в точке функции. Определение элементарных функций степенными рядами",
  "Пространство $RR^m$. Последовательности в $RR^m$ и их свойства",
  "Вектор-функции векторного переменного. Предел и непрерывность функции в точке. Непрерывность функции на множестве. Равномерная непрерывность функции на множестве и теорема Кантора",
  "Теорема о непрерывном образе компакта и ее следствия. Теорема о непрерывном образе линейно связного множества и ее следствия",
  "Дифференцирование вектор функций. Свойства операции дифференцирования. Локальная формула Тейлора и неравенство Лагранжа",
  "Интегрирование вектор функций. Оценка модуля интеграла",
  "Понятия непрерывной кривой и гладкой кривой. Спрямляемая кривая и длина кривой",
  "Частные производные функции многих переменных. Дифференцируемость в точке функции многих переменных. Теорема о непрерывности дифференцируемой функции. Теорема о существовании частных производных у дифференцируемой функции",
  "Достаточное условие дифференцируемости",
  "Дифференцирование сложной функции",
  "Производная по направлению и вектор градиент. Свойства вектора градиента",
  "Частные производные высшего порядка. Теорема о равенстве смешанных производных. Непрерывно дифференцируемые и $k$-непрерывно дифференцируемые функции",
  "Дифференциалы первого и высших порядков",
  "Формула Тейлора с остаточным членом в форме Лагранжа и форме Пеано",
  "Локальный экстремум функции многих переменных. Необходимое условие локального экстремума. Достаточное условие локального экстремума",
  "Дифференцируемые вектор-функции, матрица Якоби и якобиан",
  "Неявные функции. Теорема о неявной функции (без док-ва)",
  "Условный экстремум. Необходимое условие условного экстремума",
  "Плоские множества, измеримые по Жордану. Определение двойного интеграла. Критерий интегрируемости и достаточные условия интегрируемости. Основные свойства двойного интеграла",
  "Сведение двойного интеграла к повторному",
  "Непрерывная кривая. Спрямляемая кривая. Гладкая кривая. Длина кривой",
  "Определение криволинейных интегралов первого и второго рода по параметризованной гладкой кривой. Условия существования криволинейных интегралов",
  "Замена параметра в криволинейном интеграле первого рода. Гладкая кривая, криволинейный интеграл первого рода по гладкой кривой. Ориентированная гладкая кривая и криволинейный интеграл второго рода по ней",
  "Формула Грина",
  "Независимость криволинейного интеграла второго рода от пути интегрирования"
]

