= №49. Определение криволинейных интегралов первого и второго рода по параметризованной гладкой кривой. Условия существования криволинейных интегралов.

*Опр.* Пусть $L = L_overline(gamma)$ - глад. кривая, ф. $f(x,y)$, $P(x,y)$, $Q(x,y)$ опр. на $L$. Рассмот. разбиение отр.а $[a,b]$ т. $a = t_0 < t_1 < ... < t_n = b$ и соот. т. на кривой $M_k = (x_k, y_k) = (gamma_1(t_k), gamma_2(t_k))$, $k = 0,...,n$. Длину дуги $M_(k-1)M_k$ обозн.: $Delta s_k = limits(integral)_(t_(k-1))^(t_k) sqrt(gamma'_1(t)^2 + gamma'_2(t)^2) d t$ Диаметр разбиения: $Delta = limits(max)_(1 <= k <= n) Delta s_k $. Интег. сум.: $sigma_1 = limits(sum)_(k=1)^n f(xi_k, eta_k) Delta s_k$ ; $sigma_2 = limits(sum)_(k=1)^n P(xi_k, eta_k) Delta x_k $ ; $sigma_3 = limits(sum)_(k=1)^n Q(xi_k, eta_k) Delta y_k $ , где $Delta x_k = x_k - x_(k-1)$, $Delta y_k = y_k - y_(k-1)$. \
*Опр.* Предел сумм $sigma_1$ при $Delta -> 0$ наз. криволин. интег. первого рода: $limits(integral)_L f(x,y) d s$ Пределы сумм $sigma_2$ и $sigma_3$ наз. криволин. интег. второго рода: $limits(integral)_L P(x,y) d x $, $limits(integral)_L Q(x,y) d y $. Их сумму наз. общим криволин. интег. второго рода: $limits(integral)_L P(x,y) d x + Q(x,y) d y $

*Т. (Усл. сущ. криволин. интег.)*: Если кривая $L = L_overline(gamma)$ явл.гладкой и ф. $f$, $P$, $Q$ непр. вдоль этой кривой, то все три криволин. интег.сущ. и могут быть вычислены по форм.:
$limits(integral)_L f(x,y) d s = limits(integral)_a^b f(gamma_1(t),gamma_2(t)) sqrt(gamma'_1(t)^2 + gamma'_2(t)^2) d t $ \
$limits(integral)_L P(x,y) d x = limits(integral)_a^b P(gamma_1(t),gamma_2(t)) gamma'_1(t) d t $ \
$limits(integral)_L Q(x,y) d y = limits(integral)_a^b Q(gamma_1(t),gamma_2(t)) gamma'_2(t) d t $  \
*Док-во*: Опр. интег., стоящие в правых частях формул сущ., т.к. их подинтег. ф. непр. на отр. $[a,b]$. Докажем первое рав. Обозначим $I_1 = limits(integral)_a^b f(gamma_1(t),gamma_2(t)) sqrt(gamma'_1(t)^2 + gamma'_2(t)^2) d t$ и оценим разность $sigma_1 - I_1 = limits(sum)_(k=1)^n f(xi_k,eta_k) Delta l_k - limits(integral)_a^b f(gamma_1(t),gamma_2(t)) sqrt(gamma'_1(t)^2 + gamma'_2(t)^2) d t = limits(sum)_(k=1)^n limits(integral)_(t_(k-1))^(t_k) (f(gamma_1(tau_k),gamma_2(tau_k)) - f(gamma_1(t),gamma_2(t))) sqrt(gamma'_1(t)^2 + gamma'_2(t)^2) d t $ Т.к. ф. $gamma'_1(t)$ и $gamma'_2(t)$ непр. на $[a,b]$ и одноврем. не обр. в нуль, то $m = limits(min)_(a <= t <= b) sqrt(gamma'_1(t)^2 + gamma'_2(t)^2) > 0 $ и $Delta s_k >= m limits(integral)_(t_(k-1))^(t_k) d t = m Delta t_k $. След. $Delta t_k <= 1/m Delta s_k $ и при стремлении к нулю диам. разб. $Delta$ кривой $L$ стремится к нулю и наиб. из разн. $Delta t_k = t_k - t_(k-1)$. ф. $f(gamma_1(t), gamma_2(t))$ равн. непр. на отр. $[a, b]$, то $forall epsilon > 0 exists delta > 0$, что при $Delta < delta$ : $abs(f(gamma_1(tau_k), gamma_2(tau_k)) - f(gamma_1(t), gamma_2(t))) < epsilon/S $, где $S$ - длина кривой $L$. Тогда $abs(sigma_1 - I_1) <= epsilon/S limits(sum)_(k=1)^n limits(integral)_(t_(k-1))^(t_k) sqrt(gamma'_1(t)^2 + gamma'_2(t)^2) d t = epsilon/S limits(sum)_(k=1)^n Delta s_k = epsilon $. Таким образом интег. суммы $sigma_1$ стремятся к числу $I_1$ при $Delta -> 0$, т.e. мы доказали первое рав. Для док-ва второго рав. оценим разность $sigma_2 - I_2 = limits(sum)_(k=1)^n limits(integral)_(t_(k-1))^(t_k) (P(gamma_1(tau_k), gamma_2(tau_k)) - P(gamma_1(t), gamma_2(t))) gamma'_1(t) d t $. \ $forall epsilon > 0 exists delta > 0$, что при $Delta < delta$ : $abs(P(gamma_1(tau_k), gamma_2(tau_k)) - P(gamma_1(t), gamma_2(t))) < epsilon/(M(b-a)) $, где $M = limits(max)_(a <= t <= b) abs(gamma'_1(t))$. Тогда $abs(sigma_2 - I_2) <= epsilon/(M(b-a)) limits(sum)_(k=1)^n limits(integral)_(t_(k-1))^(t_k) abs(gamma'_1(t)) d t <= epsilon/(M(b-a)) M limits(sum)_(k=1)^n Delta t_k = epsilon $. Это означает, что интег. сум. $sigma_2$ стремятся к числу $I_2$ при $Delta -> 0$, т.е. мы док. второе равенство. Третье рав. док. аналогично
